class Character:
    def __init__(self, name, description, inventory, dialogue):
        self.name = name
        self.description = description
        self.inventory = inventory
        self.dialogue = dialogue
        
    def get_dialogue_response(self, dialogue, input_dialogue):
        if input_dialogue in dialogue:
            return dialogue[input_dialogue]
        else:
            return "I don't understand that."
        #autogenerated by Claude-3.5
        return self.dialogue
    #returns dialogue value associated with input key 

    def add_item(self, item):
        self.inventory.append(item)

    def remove_item(self, item):
        self.inventory.remove(item)
    