class Player:
    def __init__(self, name, location):
        self.name = name
        self.location = location
        self.inventory = []

    def add_item(self, item):
        print(f"You picked up {item.name}.")
        self.inventory.append(item)

    def remove_item(self, item):
        self.inventory.remove(item)

    #both functions AI-generated by Claude-3.5