import random

class Block:
    def __init__(self, shape):
        self.shape = shape

class Hole:
    def __init__(self, shape):
        self.shape = shape

def generate_puzzle():
    shapes = ["square", "circle", "triangle", "star", "archway", "rectangle", "semicircle"]
    holes = [Hole(shape) for shape in shapes]
    blocks = [Block(shape) for shape in shapes]
    random.shuffle(blocks)
    return holes, blocks

def playPuzzle(holes, blocks):
    
    for i, block in enumerate(blocks, 1):
        print(f"\nBlock {i}: {block.shape}")
        for j, hole in enumerate(holes, 1):
            print(f"{j}. {hole.shape} hole")
        
        choice = int(input("Which hole do you want to put the fitting in? ")) - 1
        
        if choice < 0 or choice >= len(holes):
            print("Invalid choice. Try again.")
            return False
        elif holes[choice].shape == block.shape and holes[choice].shape != "square":
            print("The fitting doesn't quite fit. You might have to retry this one...")
            int(input("Which hole do you want to put the fitting in? ")) - 1
        elif holes[choice].shape == "square":
            print("The fitting fits!")
        else:
            print("The fitting doesn't fit. Puzzle failed!")
            return False
    
    print("Congratulations! You've completed the puzzle!")
    return True

#code partially generated by Claude-3.5 and modified
