from character import Character
from location import location
from item import Item
from player import Player
from puzzle import playPuzzle

print("Welcome to MonkeyTime PlayFun Time Monkey Game by Games Incorporated")
print("Introduction: You believe your life is literally a video game. Yet, however, when your mother forced you to go to woke therapy, the therapist said, 'Your life is not a game. It is a nightmare. Your mother constantly worries about your mental health.' Now, he has incarcerated you in one of his dark satanic mills, and you must escape back to your mother and save her from the woke mind virus infecting the world.")
player_name =  input("What is your name? ")
#generated by Claude-3.5
player = Player(player_name)
therapist = Character("Dr. Soychild", "Your very worst nightmare, the WOKE Therapist, Dr. Soychild. He hates every signular fibre of your being. His entire life has been dedicated to keeping you weak and demoralized, so that the Establishment may remain strong and powerful.", [], {"I don't belong in here.":"Yes, you do belong in here. Your mother has asked you to remain here for the rest of your gamer life. All respawns included."}, "your gamer life")
gamer_life = Item("your gamer life", "This is the only thing you have left that hasn't been tainted by the Matrix. It is your lifeblood, your will-to-power, your gamer life; to give it away would be like selling your soul to Woke Satan.", 5000)
scene1 = location("Therapy", "You awake in a bleak white lounging room. Walking corpses of men stand all around you. The windows to the outside world, meatspace, have all been shuttered. Welcome to your new personal gamer Hell.", [], [])


